#!/bin/bash
# 在本地进行测试

mkdir -p ./build/data/

python3 ./test/case/miniob_test.py \
        --test-case-dir=./test/case/test  \
        --test-case-scores=./test/case/case-scores.json \
        --test-result-dir=./test/case/result \
        --test-result-tmp-dir=./test/case/result_tmp \
        --use-unix-socket \
        --db-code-dir=./ \
        --db-base-dir=./build/ \
        --db-data-dir=./build/data/ \
        --target-dir=./ \
        --code-type=none \
        --log=stdout \
        --compile-make-args=-j4 \
        --db-config=./etc/observer.ini